export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const CHANGE_BURGER_BUN = "CHANGE_BURGER_BUN";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const SORT_INGREDIENT = "SORT_INGREDIENT";
export const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";
