//auth actions
export const AUTH_REQUEST:"AUTH_REQUEST" = "AUTH_REQUEST";
export const AUTH_FAILED:"AUTH_FAILED" = "AUTH_FAILED";
export const POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS" = "POST_LOGIN_SUCCESS";
export const POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS" =
  "POST_REGISTER_SUCCESS";
export const POST_TOKEN_UPDATE_SUCCESS: "POST_TOKEN_UPDATE_SUCCESS" =
  "POST_TOKEN_UPDATE_SUCCESS";
export const POST_LOGOUT_SUCCESS: "POST_LOGOUT_SUCCESS" = "POST_LOGOUT_SUCCESS";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const PATCH_USER_SUCCESS: "PATCH_USER_SUCCESS" = "PATCH_USER_SUCCESS";
export const CLEAR_AUTHORIZATION: "CLEAR_AUTHORIZATION" = "CLEAR_AUTHORIZATION";

//burgerConstructor actions
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const CHANGE_BURGER_BUN: "CHANGE_BURGER_BUN" = "CHANGE_BURGER_BUN";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const SORT_INGREDIENT: "SORT_INGREDIENT" = "SORT_INGREDIENT";
export const CLEAR_INGREDIENTS: "CLEAR_INGREDIENTS" = "CLEAR_INGREDIENTS";

//burgerIngredients actions
export const GET_BURGER_INGREDIENTS_REQUEST: "GET_BURGER_INGREDIENTS_REQUEST" =
  "GET_BURGER_INGREDIENTS_REQUEST";
export const GET_BURGER_INGREDIENTS_SUCCESS: "GET_BURGER_INGREDIENTS_SUCCESS" =
  "GET_BURGER_INGREDIENTS_SUCCESS";
export const GET_BURGER_INGREDIENTS_FAILED: "GET_BURGER_INGREDIENTS_FAILED" =
  "GET_BURGER_INGREDIENTS_FAILED";
export const CHANGE_TUB: "CHANGE_TUB" = "CHANGE_TUB";

//forgot-password actions
export const POST_PASSWORD_RESET_REQUEST: "POST_PASSWORD_RESET_REQUEST" =
  "POST_PASSWORD_RESET_REQUEST";
export const POST_PASSWORD_RESET_FAILED: "POST_PASSWORD_RESET_FAILED" =
  "POST_PASSWORD_RESET_FAILED";
export const POST_PASSWORD_RESET_SUCCESS: "POST_PASSWORD_RESET_SUCCESS" =
  "POST_PASSWORD_RESET_SUCCESS";

//order actions
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const CLEAR_ORDER: "CLEAR_ORDER" = "CLEAR_ORDER";

//reset-password actions
export const POST_NEW_PASSWORD_REQUEST: "POST_NEW_PASSWORD_REQUEST" =
  "POST_NEW_PASSWORD_REQUEST";
export const POST_NEW_PASSWORD_FAILED: "POST_NEW_PASSWORD_FAILED" =
  "POST_NEW_PASSWORD_FAILED";
export const POST_NEW_PASSWORD_SUCCESS: "POST_NEW_PASSWORD_SUCCESS" =
  "POST_NEW_PASSWORD_SUCCESS";

//websocket actions
export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_START_INIT: "WS_CONNECTION_START_INIT" =
  "WS_CONNECTION_START_INIT";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_CONNECTION_FINISH: "WS_CONNECTION_FINISH" =
  "WS_CONNECTION_FINISH";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";
export const WS_GET_MESSAGE_INIT: "WS_GET_MESSAGE_INIT" = "WS_GET_MESSAGE_INIT";
